### ISSUE TITLE
error detected while processing function vimterm#open[3]

### ISSUE THREAD

**Issue by svnty** [wvffle/vimterm#24]
my vim.rc

```vim
call plug#begin('~/.vim/plugged')
Plug 'wvffle/vimterm'
call plug#end()

nnoremap <leader>t :call vimterm#toggle()<CR>
```

result of leader t

```vim
Error detected while processing function vimterm#open[3]..vimterm#init:
line    5:
E117: Unknown function: termopen
Error detected while processing function vimterm#open:
line   23:
E117: Unknown function: jobsend
Press ENTER or type command to continue
```

**Comment by wvffle** [comment]
Are you using vim or nvim? And what version?

**Comment by svnty** [comment]
> Are you using vim or nvim? And what version?

![Screen Shot 2020-06-08 at 6 15 29 pm](https://user-images.githubusercontent.com/47465827/84007626-0f0dee00-a9b4-11ea-840f-dc4cea813f7b.png)

**Comment by wvffle** [comment]
This repo is dedicated to neovim. I have no idea if it'll work under regular vim.

**Comment by svnty** [comment]
> This repo is dedicated to neovim. I have no idea if it'll work under regular vim.

That's unfortunate, hopefully I can find a nerdtree linter for vim

EDIT: sorry did I say linter, It was late last night when I was replying. I meant terminal
