### ISSUE TITLE
Calling vimterm#exec hides my buffer(s)

### ISSUE THREAD

**Issue by joereynolds** [wvffle/vimterm#5]
Any time I call `vimterm#exec` it hides the files I have been working on. Not only that but if I do multiple calls to `vimterm#exec` it creates a new split every time whereas I expected it to use the same terminal for everything?

Here's a gif!

![vimterm-bug](https://user-images.githubusercontent.com/9536682/33474987-971dae5e-d674-11e7-8c17-103bdc2b71dd.gif)

Thanks

**Comment by wvffle** [comment]
Could you please check if it works for you after the last commit?
